#!/usr/bin/env bash

    if ! type cmus >/dev/null 2>&1; then

        printf "\033c"
        echo ""
        echo "Cmus Is Not Installed!"
        echo ""
        echo "Cmus Is An Amazing Console Audio Player!"
        echo "Please Install Cmus Using Your Package-manager!"
        echo ""

        exit 1

    fi

    CMUSQ=$(cmus-remote -Q 2>/dev/null)

    if [[ -z "$CMUSQ" ]]; then

        printf "\033c"
        echo ""
        echo "Cmus Is Not Running!"
        echo "To Start Cmus, type \"cmus\" In Your Terminal!"
        echo ""

        exit 1

    fi

    CM_ST=$(cmus-remote -Q 2>/dev/null | grep "stopped")

    if [[ -n "$CM_ST" ]]; then

        printf "\033c"
        echo ""
        echo "Cmus Is Not Playing Anything!"
        echo ""

        exit 1

    fi

    CM_PA=$(cmus-remote -Q 2>/dev/null | grep "paused")

    if [[ -n "$CM_PA" ]]; then

        printf "\033c"
        echo ""
        echo "Cmus Is Not Playing Anything!"
        echo ""

        exit 1

    fi

    if ! type perl >/dev/null 2>&1; then

        printf "\033c"
        echo ""
        echo "Perl Is Not Installed!"
        echo ""
        echo "Perl Is A Required Dependency!"
        echo "Please Install Perl Using Your Package-manager!"
        echo ""

        exit 1

    fi

    perl -MURI::Escape -e 'print "$URI::Escape::VERSION\n";' &> /dev/null

    RETVAL=$?

    if [ "$RETVAL" -ne 0 ]; then

        printf "\033c"
        echo ""
        echo "Perl Module \"URI::Escape\" Is Not Installed!"
        echo ""
        echo "Module \"URI::Escape\" Is A Required Dependency!"
        echo "Please Open The Following Link For More Info,"
        echo ""
        echo -e '\e[38;5;82m'"http://stackoverflow.com/q/65865"
        echo ""
        tput sgr0

        exit 1

    fi

    if ! type wget >/dev/null 2>&1; then

        printf "\033c"
        echo ""
        echo "Wget Is Not Installed!"
        echo "Please Install Wget Using Your Package-manager!"
        echo ""

        exit 1

    fi

    TITLE=$(cmus-remote -Q 2>/dev/null | grep -m 1 'title' | cut -d " " -f 3-)

    if [[ -z "$TITLE" ]]; then

        printf "\033c"

        echo ""
        echo "Cmus can't get the title field from the file metadata!"
        echo "More information on this subject can be obtained here,"
        echo "https://en.wikipedia.org/wiki/ID3"
        echo "https://en.wikipedia.org/wiki/Tag_editor"
        echo ""

        exit 1

    fi

    ARTIST=$(cmus-remote -Q 2>/dev/null | grep -m 1 'artist' | cut -d " " -f 3-)

    if [[ -z "$ARTIST" ]]; then

        printf "\033c"

        echo ""
        echo "Cmus can't get the artist field from the file metadata!"
        echo "More information on this subject can be obtained here,"
        echo -e '\e[38;5;82m'"https://en.wikipedia.org/wiki/ID3"
        echo -e '\e[38;5;82m'"https://en.wikipedia.org/wiki/Tag_editor"
        echo ""
        tput sgr0

        exit 1

    fi

    if ! wget --spider --user-agent="Mozilla/5.0 Gecko/20100101" --no-check-certificate --quiet --timeout=30 -q "https://makeitpersonal.co" -O /dev/null; then

        printf "\033c"
        echo ""
        echo "Can Not Connect To The Site \"makeitpersonal\"!"
        echo "Make Sure Your Internet Connection Is Active!"
        echo "If The Problem Persists You Can Report It At,"
        echo "GitHub Repository Of The Project By Creating,"
        echo "An Issue There. Here Is The Link To The Repo,"
        echo ""
        echo -e '\e[38;5;82m'"https://github.com/hakerdefo/cmus-lyrics"
        echo ""
        tput sgr0
        echo "If You Don't Use GitHub You Can Report It By,"
        echo "Emailing The Author At The Following Address,"
        echo ""
        echo -e '\e[38;5;82m'"hakerdefo (at) gmail (dot) com"
        echo ""
        tput sgr0

        exit 1

    fi

    while :
    do
    time_song=$(cmus-remote -Q 2>/dev/null | grep -m 1 'duration')
    time_song=${time_song##*' '}
    position=$(cmus-remote -Q 2>/dev/null | grep -m 1 'position')
    position=${position##*' '}
    slp_time=$((time_song-position))
    ARTIST1=$(cmus-remote -Q 2>/dev/null | grep -m 1 'artist' | cut -d " " -f 3-)
    TITLE1=$(cmus-remote -Q 2>/dev/null | grep -m 1 'title' | cut -d " " -f 3-)
    ARTIST2=$(echo "$ARTIST1" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
    TITLE2=$(echo "$TITLE1" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
    SONG=$(wget --user-agent="Mozilla/5.0 Gecko/20100101" --no-check-certificate --quiet --timeout=30 -O - "https://makeitpersonal.co/lyrics?artist=$ARTIST2&title=$TITLE2")
    printf "\033c"
    printf "$TITLE1 - $ARTIST1\n$SONG"
    sleep $slp_time
    done
